/**
 * AUTO-GENERATED by sahai/scripts/build-protocols.mjs.
 * Do not edit by hand; regenerate after editing protocols/v1/*.json.
 */
/* eslint-disable */
export const PROTOCOL_MANIFEST = {
  "version": "1.0.0",
  "title": "SahAI Protocol Pack v1",
  "description": "Deterministic, citation-backed clinical decision rules for ASHA workers in rural India. Sourced from Government of India MoHFW operational guidelines, NHM ASHA modules, IMNCI chart booklets, and FOGSI/IAP standards. Every rule fires only when its inputs are explicitly observed; nothing is invented from prose.",
  "lastReviewedAt": "2026-05-06",
  "reviewers": [
    {
      "name": "SahAI Engineering",
      "role": "Author",
      "note": "Initial draft compiled from public MoHFW/NHM/IMNCI references. Pending external clinical review by an OBGYN and a paediatrician before production deployment."
    }
  ],
  "verticals": [
    "anc_danger_signs",
    "pnc_danger_signs",
    "imnci_sick_child",
    "neonatal_hbnc",
    "trauma_redflags",
    "pph",
    "fever_triage",
    "tb_dots",
    "malaria_severity",
    "snake_animal_bite",
    "mental_health_phq2",
    "ncd_pen_screen",
    "rbsk_4d",
    "idsp_reportable"
  ],
  "sources": [
    {
      "id": "MoHFW-MH-OG-2017",
      "title": "Maternal Health Operational Guidelines",
      "publisher": "Ministry of Health and Family Welfare, Government of India",
      "year": 2017
    },
    {
      "id": "MoHFW-DAKSHATA-2017",
      "title": "Dakshata: Empowering providers for improved MNH care during institutional deliveries",
      "publisher": "MoHFW, Government of India",
      "year": 2017
    },
    {
      "id": "MoHFW-HBNC-2014",
      "title": "Home Based Newborn Care: Operational Guidelines (revised)",
      "publisher": "MoHFW, Government of India",
      "year": 2014
    },
    {
      "id": "MoHFW-IMNCI-2018",
      "title": "Integrated Management of Neonatal and Childhood Illness (IMNCI) Chart Booklet",
      "publisher": "MoHFW, Government of India",
      "year": 2018
    },
    {
      "id": "MoHFW-RBSK-2013",
      "title": "Rashtriya Bal Swasthya Karyakram operational framework",
      "publisher": "MoHFW, Government of India",
      "year": 2013
    },
    {
      "id": "MoHFW-RNTCP-2019",
      "title": "Index-TB and TB Programme Technical and Operational Guidelines",
      "publisher": "Central TB Division, MoHFW",
      "year": 2019
    },
    {
      "id": "MoHFW-MALARIA-2016",
      "title": "National Drug Policy on Malaria",
      "publisher": "National Vector Borne Disease Control Programme, MoHFW",
      "year": 2016
    },
    {
      "id": "MoHFW-PEN-2017",
      "title": "Operational Guidelines for Prevention, Screening, and Control of Common NCDs (PEN package)",
      "publisher": "MoHFW, Government of India",
      "year": 2017
    },
    {
      "id": "MoHFW-IDSP-2018",
      "title": "Integrated Disease Surveillance Programme - Manual for ASHA/ANM",
      "publisher": "National Centre for Disease Control, MoHFW",
      "year": 2018
    },
    {
      "id": "MoHFW-SNAKEBITE-2017",
      "title": "National Snakebite Management Protocol",
      "publisher": "MoHFW, Government of India",
      "year": 2017
    },
    {
      "id": "FOGSI-PE-2017",
      "title": "FOGSI Good Clinical Practice Recommendations on Pre-eclampsia and Eclampsia",
      "publisher": "Federation of Obstetric and Gynaecological Societies of India",
      "year": 2017
    },
    {
      "id": "WHO-PHQ2",
      "title": "Patient Health Questionnaire-2 (mhGAP)",
      "publisher": "World Health Organization",
      "year": 2016
    }
  ]
} as const;

export const PROTOCOL_TTT = {
  "version": "1.0.0",
  "description": "Default time-to-treatment (in minutes) per severity band when a fired rule does not specify its own ttt_minutes. The engine picks the minimum across all fired rules.",
  "defaults": {
    "CRITICAL": 30,
    "HIGH": 240,
    "MODERATE": 1440,
    "LOW": 10080
  },
  "urgency_score": {
    "description": "Composite urgency formula evaluated by the supervisor dashboard. Higher = more urgent.",
    "formula": "level_weight + life_threat_bonus + age_modifier + pregnancy_modifier + 1000 / max(ttt_minutes_remaining, 1)",
    "level_weight": {
      "LOW": 0,
      "MODERATE": 25,
      "HIGH": 60,
      "CRITICAL": 100
    },
    "life_threat_bonus": 25,
    "age_modifiers": {
      "infant_under_2_months": 15,
      "child_under_5_years": 10,
      "elderly_over_60_years": 5
    },
    "pregnancy_modifier": 10
  }
} as const;

export const PROTOCOL_RULES = [
  {
    "id": "ANC.PE.SEVERE",
    "vertical": "ANC",
    "label": {
      "en": "Severe pre-eclampsia (BP >= 160/110)",
      "hi": "गंभीर प्री-एक्लेम्पसिया"
    },
    "applies_to": {
      "isPregnant": true
    },
    "trigger": {
      "any_of": [
        {
          "vitals.systolicBP_gte": 160
        },
        {
          "vitals.diastolicBP_gte": 110
        }
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 30,
    "first_response_actions": [
      {
        "id": "POSITION_LEFT_LATERAL",
        "text": {
          "en": "Lay patient in the left lateral position."
        }
      },
      {
        "id": "RECHECK_BP_5MIN",
        "text": {
          "en": "Recheck BP after 5 minutes of rest; record both readings."
        }
      },
      {
        "id": "CALL_108_OBSTETRIC",
        "text": {
          "en": "Call 108 — request obstetric-equipped ambulance and inform receiving facility."
        }
      },
      {
        "id": "MAGNESIUM_LOADING_AT_PHC",
        "text": {
          "en": "Communicate to PHC/CHC: prepare loading dose of MgSO4 per FOGSI/MoHFW protocol."
        }
      }
    ],
    "rationale": "BP >= 160/110 mmHg in pregnancy meets the diagnostic threshold for severe pre-eclampsia and risks eclampsia/stroke; FOGSI guidelines require immediate transfer with MgSO4 ready at receiving facility.",
    "source": {
      "doc": "FOGSI-PE-2017",
      "section": "Severe pre-eclampsia management"
    }
  },
  {
    "id": "ANC.PE.SUSPECTED",
    "vertical": "ANC",
    "label": {
      "en": "Suspected pre-eclampsia (BP >= 140/90 + symptoms)",
      "hi": "प्री-एक्लेम्पसिया का संदेह"
    },
    "applies_to": {
      "isPregnant": true
    },
    "trigger": {
      "all_of": [
        {
          "any_of": [
            {
              "vitals.systolicBP_gte": 140
            },
            {
              "vitals.diastolicBP_gte": 90
            }
          ]
        },
        {
          "any_symptom_in": [
            "headache",
            "blurred vision",
            "visual disturbance",
            "edema",
            "swelling face",
            "swelling hands",
            "epigastric pain",
            "right upper quadrant",
            "sirdard",
            "dhundla dikhna"
          ]
        }
      ]
    },
    "escalates_to": "HIGH",
    "ttt_minutes": 120,
    "first_response_actions": [
      {
        "id": "RECHECK_BP",
        "text": {
          "en": "Recheck BP after 5 minutes of rest in left lateral position."
        }
      },
      {
        "id": "DIPSTICK_PROTEINURIA",
        "text": {
          "en": "If urine dipstick available, test for proteinuria; >= 1+ supports diagnosis."
        }
      },
      {
        "id": "REFER_PHC_TODAY",
        "text": {
          "en": "Refer to PHC today for obstetric review and lab tests."
        }
      }
    ],
    "rationale": "BP >= 140/90 with at least one prodromal symptom is the FOGSI/MoHFW threshold for suspected pre-eclampsia and warrants same-day obstetric assessment.",
    "source": {
      "doc": "FOGSI-PE-2017"
    }
  },
  {
    "id": "ANC.HEMORRHAGE.ANTEPARTUM",
    "vertical": "ANC",
    "label": {
      "en": "Antepartum haemorrhage",
      "hi": "गर्भावस्था में रक्तस्राव"
    },
    "applies_to": {
      "isPregnant": true,
      "gestationalWeeksMin": 20
    },
    "trigger": {
      "any_symptom_in": [
        "vaginal bleeding",
        "bleeding pv",
        "per vaginal bleeding",
        "khoon aa raha",
        "blood from vagina"
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 30,
    "first_response_actions": [
      {
        "id": "DO_NOT_PV_EXAM",
        "text": {
          "en": "Do NOT perform a per-vaginal examination at home."
        }
      },
      {
        "id": "LEFT_LATERAL",
        "text": {
          "en": "Place patient in the left lateral position."
        }
      },
      {
        "id": "PAD_COUNT",
        "text": {
          "en": "Note number of soaked pads; report to receiving facility."
        }
      },
      {
        "id": "CALL_108_OBSTETRIC",
        "text": {
          "en": "Call 108 — request obstetric ambulance immediately."
        }
      }
    ],
    "rationale": "Any vaginal bleeding after 20 weeks may signal placenta praevia or abruption; both are obstetric emergencies that need facility-based diagnosis and possible operative delivery.",
    "source": {
      "doc": "MoHFW-MH-OG-2017",
      "section": "Antepartum haemorrhage"
    }
  },
  {
    "id": "ANC.REDUCED.FETAL.MOVEMENTS",
    "vertical": "ANC",
    "label": {
      "en": "Reduced fetal movements",
      "hi": "बच्चे की हलचल कम"
    },
    "applies_to": {
      "isPregnant": true,
      "gestationalWeeksMin": 28
    },
    "trigger": {
      "any_symptom_in": [
        "reduced fetal movement",
        "no fetal movement",
        "baby not moving",
        "bachcha hil nahi raha",
        "bachcha kam hil raha"
      ]
    },
    "escalates_to": "HIGH",
    "ttt_minutes": 240,
    "first_response_actions": [
      {
        "id": "LEFT_LATERAL_COUNT",
        "text": {
          "en": "Ask mother to lie on left side and count movements for 1 hour; expect at least 4 movements."
        }
      },
      {
        "id": "REFER_PHC_TODAY",
        "text": {
          "en": "If movements remain reduced, refer to PHC today for fetal heart-rate check / NST."
        }
      }
    ],
    "rationale": "Reduced fetal movements after 28 weeks correlate with hypoxia/IUGR; same-day fetal monitoring is required per MoHFW MH operational guidelines.",
    "source": {
      "doc": "MoHFW-MH-OG-2017",
      "section": "Daily Fetal Movement Count"
    }
  },
  {
    "id": "ANC.CONVULSIONS.ECLAMPSIA",
    "vertical": "ANC",
    "label": {
      "en": "Eclampsia (convulsion in pregnancy or postpartum)",
      "hi": "एक्लेम्पसिया - दौरे"
    },
    "applies_to": {
      "isPregnant": true
    },
    "trigger": {
      "any_symptom_in": [
        "convulsion",
        "fitting",
        "seizure",
        "daura",
        "ankhain ulti"
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 0,
    "first_response_actions": [
      {
        "id": "PROTECT_AIRWAY",
        "text": {
          "en": "Lay the woman on her left side; do NOT put anything in the mouth."
        }
      },
      {
        "id": "PROTECT_FROM_INJURY",
        "text": {
          "en": "Move sharp objects away; cushion the head."
        }
      },
      {
        "id": "CALL_108_OBSTETRIC",
        "text": {
          "en": "Call 108 — eclampsia is a CRITICAL obstetric emergency."
        }
      },
      {
        "id": "MGSO4_LOAD_AT_PHC",
        "text": {
          "en": "Communicate to receiving facility: prepare MgSO4 loading dose per Dakshata protocol."
        }
      }
    ],
    "rationale": "Convulsions in pregnancy are presumed eclampsia until proven otherwise; mortality is high without prompt MgSO4 and operative delivery.",
    "source": {
      "doc": "MoHFW-DAKSHATA-2017",
      "section": "Eclampsia management"
    }
  },
  {
    "id": "ANC.SEVERE.ANAEMIA",
    "vertical": "ANC",
    "label": {
      "en": "Severe anaemia in pregnancy (Hb < 7 g/dL)",
      "hi": "गर्भावस्था में गंभीर खून की कमी"
    },
    "applies_to": {
      "isPregnant": true
    },
    "trigger": {
      "vitals.haemoglobin_lt": 7
    },
    "escalates_to": "HIGH",
    "ttt_minutes": 1440,
    "first_response_actions": [
      {
        "id": "REFER_PHC_FOR_IV_IRON",
        "text": {
          "en": "Refer to PHC/CHC for IV iron sucrose / blood transfusion as per MAA-Anaemia Mukt Bharat protocol."
        }
      },
      {
        "id": "DAILY_IFA",
        "text": {
          "en": "Continue daily IFA and counsel on iron-rich foods."
        }
      }
    ],
    "rationale": "Hb < 7 g/dL is the MoHFW threshold for severe anaemia requiring institutional management to prevent peripartum cardiac failure and intra-partum haemorrhage.",
    "source": {
      "doc": "MoHFW-MH-OG-2017",
      "section": "Anaemia Mukt Bharat"
    }
  },
  {
    "id": "ANC.SEVERE.PROM.OR.PRETERM",
    "vertical": "ANC",
    "label": {
      "en": "PROM or preterm labour (< 37 weeks)",
      "hi": "पानी फटना / समय से पहले प्रसव"
    },
    "applies_to": {
      "isPregnant": true,
      "gestationalWeeksMax": 36
    },
    "trigger": {
      "any_symptom_in": [
        "water broken",
        "leaking pv",
        "rupture of membranes",
        "labour pain",
        "regular contractions",
        "prasav peeda",
        "paani fata"
      ]
    },
    "escalates_to": "HIGH",
    "ttt_minutes": 120,
    "first_response_actions": [
      {
        "id": "LEFT_LATERAL",
        "text": {
          "en": "Place mother in left lateral position; do NOT do internal exam."
        }
      },
      {
        "id": "CLEAN_PAD",
        "text": {
          "en": "Use a clean pad; note the colour of the fluid (clear / meconium / blood-stained)."
        }
      },
      {
        "id": "REFER_FRU",
        "text": {
          "en": "Refer to FRU/CHC — preterm needs steroids + neonatal-care readiness."
        }
      }
    ],
    "rationale": "Preterm PROM and labour < 37 weeks need facility delivery, antenatal steroids, and neonatal resuscitation readiness per Dakshata.",
    "source": {
      "doc": "MoHFW-DAKSHATA-2017",
      "section": "PROM and preterm labour"
    }
  },
  {
    "id": "FEVER.HYPERPYREXIA",
    "vertical": "FEVER",
    "label": {
      "en": "Hyperpyrexia (>= 40 °C / 104 °F)",
      "hi": "बहुत तेज़ बुखार"
    },
    "trigger": {
      "vitals.temperature_gte": 40
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 60,
    "first_response_actions": [
      {
        "id": "PARACETAMOL_NOW",
        "text": {
          "en": "Give paracetamol weight-based dose now (10–15 mg/kg)."
        }
      },
      {
        "id": "TEPID_SPONGING",
        "text": {
          "en": "Tepid sponging with lukewarm water; do NOT use cold water or alcohol."
        }
      },
      {
        "id": "REFER_NOW",
        "text": {
          "en": "Refer to PHC/CHC now; rule out cerebral malaria, severe sepsis, dengue shock."
        }
      }
    ],
    "rationale": "Core temperature >= 40 °C risks febrile seizures, dehydration, and signals severe infection or heatstroke; same-day facility evaluation required.",
    "source": {
      "doc": "MoHFW-IMNCI-2018",
      "section": "Fever - Severe disease"
    }
  },
  {
    "id": "FEVER.PERSISTENT.PROLONGED",
    "vertical": "FEVER",
    "label": {
      "en": "Persistent fever > 7 days",
      "hi": "लगातार 7 दिन से ज़्यादा बुखार"
    },
    "trigger": {
      "any_symptom_in": [
        "fever for 7 days",
        "fever for 8 days",
        "fever for 10 days",
        "two weeks fever",
        "satah dino se bukhar",
        "saat din se bukhar"
      ]
    },
    "escalates_to": "HIGH",
    "ttt_minutes": 1440,
    "first_response_actions": [
      {
        "id": "MALARIA_TYPHOID_TB_WORKUP",
        "text": {
          "en": "Refer to PHC/CHC for malaria smear/RDT, dengue/typhoid serology, and TB screening."
        }
      }
    ],
    "rationale": "Fever >= 7 days warrants laboratory workup for malaria, typhoid, dengue, and TB per IDSP and RNTCP guidelines.",
    "source": {
      "doc": "MoHFW-IDSP-2018",
      "section": "Fever Surveillance"
    }
  },
  {
    "id": "FEVER.WITH.RASH",
    "vertical": "FEVER",
    "label": {
      "en": "Fever with rash (measles / dengue)",
      "hi": "बुखार के साथ दाने"
    },
    "trigger": {
      "all_of": [
        {
          "vitals.temperature_gte": 38
        },
        {
          "any_symptom_in": [
            "rash",
            "petechiae",
            "purpura",
            "haemorrhagic spots",
            "khoon ke daane",
            "lal daane"
          ]
        }
      ]
    },
    "escalates_to": "HIGH",
    "ttt_minutes": 240,
    "first_response_actions": [
      {
        "id": "ISOLATE_NOTIFY",
        "text": {
          "en": "Isolate patient if measles is suspected; notify ANM/MO for IDSP reporting."
        }
      },
      {
        "id": "REFER_FOR_CBC_NS1",
        "text": {
          "en": "Refer to PHC/CHC for CBC + NS1 antigen and platelet trend."
        }
      }
    ],
    "rationale": "Fever with rash + petechiae raises concern for severe dengue / measles; both are IDSP-notifiable and require platelet monitoring.",
    "source": {
      "doc": "MoHFW-IDSP-2018",
      "section": "Notifiable Diseases"
    }
  },
  {
    "id": "IDSP.AFP",
    "vertical": "IDSP",
    "label": {
      "en": "Acute flaccid paralysis (< 15 yr)",
      "hi": "अचानक लकवा (15 वर्ष से कम)"
    },
    "applies_to": {
      "ageYearsMax": 15
    },
    "trigger": {
      "any_symptom_in": [
        "sudden weakness limb",
        "flaccid paralysis",
        "cannot move legs",
        "polio-like",
        "lakwa",
        "afp"
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 60,
    "first_response_actions": [
      {
        "id": "IDSP_REPORT_TODAY",
        "text": {
          "en": "Report to ANM/MO today; AFP is reportable within 24 hours under polio surveillance."
        }
      },
      {
        "id": "REFER_PEDIATRIC",
        "text": {
          "en": "Refer to paediatric facility for stool samples and neurological assessment."
        }
      }
    ],
    "rationale": "AFP in under-15s requires immediate notification to maintain India's polio-free status.",
    "source": {
      "doc": "MoHFW-IDSP-2018",
      "section": "AFP Surveillance"
    }
  },
  {
    "id": "IDSP.AES.JE",
    "vertical": "IDSP",
    "label": {
      "en": "Acute encephalitis syndrome (AES/JE)",
      "hi": "तीव्र मस्तिष्क ज्वर"
    },
    "trigger": {
      "all_of": [
        {
          "vitals.temperature_gte": 38.5
        },
        {
          "any_symptom_in": [
            "altered mental status",
            "convulsion",
            "neck rigidity",
            "behoshi",
            "daura"
          ]
        }
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 60,
    "first_response_actions": [
      {
        "id": "REFER_TERTIARY",
        "text": {
          "en": "Refer urgently to a paediatric/medical college for LP and supportive care."
        }
      },
      {
        "id": "IDSP_NOTIFY",
        "text": {
          "en": "Notify IDSP unit; AES/JE is mandatorily reportable."
        }
      }
    ],
    "rationale": "AES carries high case fatality; early supportive care and JE surveillance are part of the IDSP weekly form.",
    "source": {
      "doc": "MoHFW-IDSP-2018",
      "section": "AES/JE"
    }
  },
  {
    "id": "IDSP.MEASLES.RUBELLA",
    "vertical": "IDSP",
    "label": {
      "en": "Measles / rubella outbreak suspect",
      "hi": "खसरा / रूबेला"
    },
    "trigger": {
      "all_of": [
        {
          "any_symptom_in": [
            "rash",
            "lal daane",
            "measles rash"
          ]
        },
        {
          "vitals.temperature_gte": 38
        },
        {
          "any_symptom_in": [
            "cough",
            "coryza",
            "conjunctivitis"
          ]
        }
      ]
    },
    "escalates_to": "HIGH",
    "ttt_minutes": 240,
    "first_response_actions": [
      {
        "id": "ISOLATE_VITAMIN_A",
        "text": {
          "en": "Isolate the case; give Vitamin A per IMNCI."
        }
      },
      {
        "id": "IDSP_LINE_LIST",
        "text": {
          "en": "Line-list household and school contacts; report to MO for outbreak response."
        }
      }
    ],
    "rationale": "Measles/rubella is targeted for elimination; any suspected case triggers an outbreak investigation.",
    "source": {
      "doc": "MoHFW-IDSP-2018",
      "section": "Measles-Rubella Elimination"
    }
  },
  {
    "id": "IMNCI.GENERAL.DANGER_SIGN",
    "vertical": "IMNCI",
    "label": {
      "en": "General danger sign (child 2 mo – 5 yr)",
      "hi": "बच्चे का खतरनाक संकेत"
    },
    "applies_to": {
      "ageMonthsMin": 2,
      "ageMonthsMax": 59
    },
    "trigger": {
      "any_symptom_in": [
        "unable to drink",
        "unable to breastfeed",
        "convulsion",
        "convulsing",
        "lethargic",
        "unconscious",
        "vomits everything",
        "stridor at rest",
        "kuch nahi pee raha",
        "behoshi"
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 0,
    "first_response_actions": [
      {
        "id": "REFER_URGENT",
        "text": {
          "en": "Refer URGENTLY to nearest hospital with IMNCI-trained team."
        }
      },
      {
        "id": "GIVE_PARACETAMOL_IF_FEVER",
        "text": {
          "en": "If temp >= 38.5 °C, give paracetamol per IMNCI dose chart."
        }
      },
      {
        "id": "WARM_AND_BREASTFEED",
        "text": {
          "en": "Keep the child warm and continue breastfeeding if able."
        }
      },
      {
        "id": "PRE_REFERRAL_ABX",
        "text": {
          "en": "If trained: give first dose of pre-referral antibiotic (e.g. IM amoxicillin) per IMNCI guideline."
        }
      }
    ],
    "rationale": "MoHFW IMNCI Chart Booklet: any single general danger sign in a 2 mo – 5 yr child mandates urgent referral and pre-referral treatment.",
    "source": {
      "doc": "MoHFW-IMNCI-2018",
      "section": "General Danger Signs"
    }
  },
  {
    "id": "IMNCI.PNEUMONIA.SEVERE",
    "vertical": "IMNCI",
    "label": {
      "en": "Severe pneumonia (chest indrawing / stridor)",
      "hi": "गंभीर निमोनिया"
    },
    "applies_to": {
      "ageMonthsMin": 2,
      "ageMonthsMax": 59
    },
    "trigger": {
      "any_of": [
        {
          "any_symptom_in": [
            "chest indrawing",
            "lower chest indrawing",
            "stridor",
            "saans seene mein dabna"
          ]
        },
        {
          "all_of": [
            {
              "any_symptom_in": [
                "cough",
                "fast breathing",
                "respiratory distress"
              ]
            },
            {
              "any_of": [
                {
                  "vitals.respiratoryRate_gte": 50
                }
              ]
            }
          ]
        }
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 30,
    "first_response_actions": [
      {
        "id": "REFER_URGENT",
        "text": {
          "en": "Refer URGENTLY for hospital treatment."
        }
      },
      {
        "id": "PRE_REFERRAL_ABX_IMNCI",
        "text": {
          "en": "If trained: give first dose of IM antibiotic per IMNCI dose chart."
        }
      },
      {
        "id": "KEEP_WARM_BREASTFEED",
        "text": {
          "en": "Keep warm; continue breastfeeding."
        }
      }
    ],
    "rationale": "Chest indrawing or stridor at rest is the IMNCI definition of severe pneumonia and mandates pre-referral antibiotic + urgent transfer.",
    "source": {
      "doc": "MoHFW-IMNCI-2018",
      "section": "Cough or Difficult Breathing"
    }
  },
  {
    "id": "IMNCI.PNEUMONIA.NONSEVERE",
    "vertical": "IMNCI",
    "label": {
      "en": "Pneumonia (non-severe, fast breathing)",
      "hi": "निमोनिया - तेज़ साँस"
    },
    "applies_to": {
      "ageMonthsMin": 12,
      "ageMonthsMax": 59
    },
    "trigger": {
      "all_of": [
        {
          "any_symptom_in": [
            "cough",
            "fast breathing",
            "khansi"
          ]
        },
        {
          "vitals.respiratoryRate_gte": 40
        }
      ]
    },
    "escalates_to": "HIGH",
    "ttt_minutes": 240,
    "first_response_actions": [
      {
        "id": "ORAL_AMOX",
        "text": {
          "en": "Give oral amoxicillin per IMNCI dose chart for 5 days."
        }
      },
      {
        "id": "FOLLOW_UP_3_DAYS",
        "text": {
          "en": "Follow up in 3 days; advise return if breathing worsens, child cannot drink, or fever persists."
        }
      }
    ],
    "rationale": "RR >= 40 in 12–59 mo with cough is non-severe pneumonia per IMNCI; treat with oral amoxicillin and follow up in 3 days.",
    "source": {
      "doc": "MoHFW-IMNCI-2018",
      "section": "Cough or Difficult Breathing"
    }
  },
  {
    "id": "IMNCI.DIARRHOEA.SEVERE_DEHYDRATION",
    "vertical": "IMNCI",
    "label": {
      "en": "Severe dehydration",
      "hi": "गंभीर पानी की कमी"
    },
    "applies_to": {
      "ageMonthsMax": 59
    },
    "trigger": {
      "any_symptom_in": [
        "sunken eyes",
        "skin pinch goes back very slowly",
        "lethargic",
        "unable to drink",
        "very thirsty",
        "ankhain dhansi",
        "twacha pakad ke chodne par der"
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 30,
    "first_response_actions": [
      {
        "id": "PLAN_C_REFER",
        "text": {
          "en": "Plan C: refer urgently for IV fluids; en route give frequent sips of ORS."
        }
      },
      {
        "id": "GIVE_ZINC_AT_FACILITY",
        "text": {
          "en": "Once stable, ensure ORS + zinc per IMNCI."
        }
      }
    ],
    "rationale": "IMNCI Plan C: any two of the four severe dehydration signs requires IV fluids; ORS en route is safe.",
    "source": {
      "doc": "MoHFW-IMNCI-2018",
      "section": "Diarrhoea - Plan C"
    }
  },
  {
    "id": "IMNCI.DIARRHOEA.SOME_DEHYDRATION",
    "vertical": "IMNCI",
    "label": {
      "en": "Some dehydration",
      "hi": "कुछ पानी की कमी"
    },
    "applies_to": {
      "ageMonthsMax": 59
    },
    "trigger": {
      "any_symptom_in": [
        "thirsty",
        "restless",
        "irritable",
        "sunken eyes",
        "skin pinch goes back slowly"
      ]
    },
    "escalates_to": "MODERATE",
    "ttt_minutes": 1440,
    "first_response_actions": [
      {
        "id": "PLAN_B_ORS",
        "text": {
          "en": "Plan B: ORS 75 mL/kg over 4 hours under observation; reassess."
        }
      },
      {
        "id": "ZINC_14_DAYS",
        "text": {
          "en": "Zinc 20 mg daily x 14 days (10 mg if < 6 mo)."
        }
      }
    ],
    "rationale": "IMNCI Plan B for some dehydration: supervised ORS + zinc; reassess in 4 hours for response or escalation.",
    "source": {
      "doc": "MoHFW-IMNCI-2018",
      "section": "Diarrhoea - Plan B"
    }
  },
  {
    "id": "IMNCI.SAM",
    "vertical": "IMNCI",
    "label": {
      "en": "Severe acute malnutrition (MUAC < 115 mm or oedema)",
      "hi": "गंभीर तीव्र कुपोषण"
    },
    "applies_to": {
      "ageMonthsMin": 6,
      "ageMonthsMax": 59
    },
    "trigger": {
      "any_of": [
        {
          "vitals.muacMm_lt": 115
        },
        {
          "any_symptom_in": [
            "bilateral pitting oedema",
            "feet swelling",
            "hand swelling"
          ]
        }
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 240,
    "first_response_actions": [
      {
        "id": "REFER_NRC",
        "text": {
          "en": "Refer to Nutrition Rehabilitation Centre (NRC) / facility-based SAM care."
        }
      },
      {
        "id": "APPETITE_TEST",
        "text": {
          "en": "Counsel mother on appetite test and continued breastfeeding en route."
        }
      }
    ],
    "rationale": "MUAC < 115 mm or bilateral pitting oedema defines SAM; NRC admission per RBSK/MAA.",
    "source": {
      "doc": "MoHFW-IMNCI-2018",
      "section": "Malnutrition"
    }
  },
  {
    "id": "IMNCI.MAM",
    "vertical": "IMNCI",
    "label": {
      "en": "Moderate acute malnutrition (MUAC 115–124 mm)",
      "hi": "मध्यम तीव्र कुपोषण"
    },
    "applies_to": {
      "ageMonthsMin": 6,
      "ageMonthsMax": 59
    },
    "trigger": {
      "all_of": [
        {
          "vitals.muacMm_gte": 115
        },
        {
          "vitals.muacMm_lt": 125
        }
      ]
    },
    "escalates_to": "HIGH",
    "ttt_minutes": 1440,
    "first_response_actions": [
      {
        "id": "ENROLL_AWC_VHND",
        "text": {
          "en": "Enrol in AWC supplementary feeding; review weekly at VHND."
        }
      },
      {
        "id": "DEWORM_AND_IFA",
        "text": {
          "en": "Deworming and IFA syrup per RBSK schedule."
        }
      }
    ],
    "rationale": "MUAC 115–124 mm is MAM; community-based management with weekly follow-up.",
    "source": {
      "doc": "MoHFW-IMNCI-2018",
      "section": "Malnutrition"
    }
  },
  {
    "id": "MALARIA.SEVERE",
    "vertical": "MALARIA",
    "label": {
      "en": "Severe malaria (danger sign / cerebral)",
      "hi": "गंभीर मलेरिया"
    },
    "trigger": {
      "all_of": [
        {
          "any_symptom_in": [
            "fever",
            "rigors",
            "bukhar",
            "kapkapi",
            "shivering"
          ]
        },
        {
          "any_of": [
            {
              "any_symptom_in": [
                "unconscious",
                "convulsion",
                "yellow eyes",
                "no urine",
                "very weak",
                "behoshi"
              ]
            },
            {
              "vitals.spO2_lt": 92
            },
            {
              "vitals.temperature_gte": 39.5
            }
          ]
        }
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 60,
    "first_response_actions": [
      {
        "id": "RDT_NOW",
        "text": {
          "en": "Perform bivalent malaria RDT now if available; record result."
        }
      },
      {
        "id": "ARTESUNATE_AT_PHC",
        "text": {
          "en": "Communicate to PHC: prepare IV artesunate per National Drug Policy on Malaria."
        }
      },
      {
        "id": "REFER_NOW",
        "text": {
          "en": "Refer urgently to PHC/CHC for parenteral therapy."
        }
      }
    ],
    "rationale": "Severe malaria (one or more WHO criteria) needs IV artesunate within an hour; in P. falciparum-endemic blocks the index of suspicion is high.",
    "source": {
      "doc": "MoHFW-MALARIA-2016",
      "section": "Severe Malaria Management"
    }
  },
  {
    "id": "MALARIA.UNCOMPLICATED.SUSPECT",
    "vertical": "MALARIA",
    "label": {
      "en": "Uncomplicated malaria suspect (fever + endemic block)",
      "hi": "मलेरिया का संदेह"
    },
    "trigger": {
      "all_of": [
        {
          "any_symptom_in": [
            "fever",
            "bukhar",
            "rigors"
          ]
        },
        {
          "vitals.temperature_gte": 38
        }
      ]
    },
    "escalates_to": "MODERATE",
    "ttt_minutes": 1440,
    "first_response_actions": [
      {
        "id": "RDT_TODAY",
        "text": {
          "en": "Perform RDT today; if positive, give ACT per Pf/Pv-specific schedule."
        }
      },
      {
        "id": "PARACETAMOL",
        "text": {
          "en": "Give paracetamol weight-based; advise plenty of fluids."
        }
      },
      {
        "id": "RETURN_IF_WORSE",
        "text": {
          "en": "Return immediately if drowsy, vomiting, no urine, breathing fast."
        }
      }
    ],
    "rationale": "ASHA-led RDT + ACT is the operational standard in malaria-endemic blocks; counsel return for danger signs to catch progression.",
    "source": {
      "doc": "MoHFW-MALARIA-2016"
    }
  },
  {
    "id": "MENTAL.PHQ2.POSITIVE",
    "vertical": "MENTAL_HEALTH",
    "label": {
      "en": "PHQ-2 positive (possible depression)",
      "hi": "अवसाद की संभावना"
    },
    "trigger": {
      "any_of": [
        {
          "any_symptom_in": [
            "feeling down",
            "loss of interest",
            "anhedonia",
            "no interest in activities",
            "udaasi",
            "kuch acha nahi lagta",
            "sad most days"
          ]
        }
      ]
    },
    "escalates_to": "MODERATE",
    "ttt_minutes": 1440,
    "first_response_actions": [
      {
        "id": "PHQ9_AT_PHC",
        "text": {
          "en": "Refer to PHC/CHC mental-health team for PHQ-9 confirmation and counselling."
        }
      },
      {
        "id": "BRIEF_SUPPORT",
        "text": {
          "en": "Listen non-judgementally; reinforce that help is available; share Tele-MANAS 14416 hotline."
        }
      },
      {
        "id": "RULE_OUT_SUICIDAL_INTENT",
        "text": {
          "en": "Ask explicitly about self-harm thoughts; if positive, escalate to HIGH and refer same day."
        }
      }
    ],
    "rationale": "PHQ-2 has high sensitivity for major depressive disorder; positive screen requires PHQ-9 confirmation and active suicide-risk assessment.",
    "source": {
      "doc": "WHO-PHQ2"
    }
  },
  {
    "id": "MENTAL.SUICIDAL.IDEATION",
    "vertical": "MENTAL_HEALTH",
    "label": {
      "en": "Suicidal ideation / self-harm intent",
      "hi": "आत्महत्या के विचार"
    },
    "trigger": {
      "any_symptom_in": [
        "wants to die",
        "self harm",
        "suicide thoughts",
        "khud ko nuksan",
        "marna chahta hu",
        "khudkushi",
        "thoughts of suicide"
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 60,
    "first_response_actions": [
      {
        "id": "STAY_WITH",
        "text": {
          "en": "Stay with the person; remove access to pesticides, ropes, sharp items."
        }
      },
      {
        "id": "TELE_MANAS_14416",
        "text": {
          "en": "Call Tele-MANAS 14416 immediately for live counsellor support."
        }
      },
      {
        "id": "REFER_DMHP",
        "text": {
          "en": "Refer to District Mental Health Programme today; involve family safely."
        }
      }
    ],
    "rationale": "Active suicidal ideation is a psychiatric emergency. WHO mhGAP and India's NMHP mandate same-day specialist contact and means restriction.",
    "source": {
      "doc": "WHO-PHQ2"
    }
  },
  {
    "id": "NCD.HTN.SEVERE",
    "vertical": "NCD",
    "label": {
      "en": "Severe hypertension (BP >= 180/110)",
      "hi": "बहुत ज़्यादा बीपी"
    },
    "applies_to": {
      "isPregnant": false
    },
    "trigger": {
      "any_of": [
        {
          "vitals.systolicBP_gte": 180
        },
        {
          "vitals.diastolicBP_gte": 110
        }
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 30,
    "first_response_actions": [
      {
        "id": "REST_15MIN_RECHECK",
        "text": {
          "en": "Sit the patient calmly for 15 minutes; recheck BP on the other arm."
        }
      },
      {
        "id": "REFER_PHC_TODAY",
        "text": {
          "en": "If still >= 180/110 or any target-organ symptom (chest pain, breathlessness, vision change), refer to PHC/CHC same day."
        }
      }
    ],
    "rationale": "PEN protocol: BP >= 180/110 in non-pregnant adults is hypertensive crisis and warrants same-day evaluation.",
    "source": {
      "doc": "MoHFW-PEN-2017",
      "section": "Hypertension"
    }
  },
  {
    "id": "NCD.HTN.STAGE2",
    "vertical": "NCD",
    "label": {
      "en": "Hypertension stage 2 (>= 160/100)",
      "hi": "उच्च रक्तचाप - दूसरा चरण"
    },
    "applies_to": {
      "isPregnant": false
    },
    "trigger": {
      "any_of": [
        {
          "vitals.systolicBP_gte": 160
        },
        {
          "vitals.diastolicBP_gte": 100
        }
      ]
    },
    "escalates_to": "HIGH",
    "ttt_minutes": 240,
    "first_response_actions": [
      {
        "id": "REFER_PHC_TODAY",
        "text": {
          "en": "Refer to PHC for same-day medical officer review and PEN package initiation."
        }
      },
      {
        "id": "LIFESTYLE_COUNSEL",
        "text": {
          "en": "Salt < 5 g/day, no tobacco, daily 30-min walk; explain medication adherence importance."
        }
      }
    ],
    "rationale": "Hypertension stage 2 in PEN package needs medical-officer review and likely two-drug therapy.",
    "source": {
      "doc": "MoHFW-PEN-2017"
    }
  },
  {
    "id": "NCD.HTN.STAGE1",
    "vertical": "NCD",
    "label": {
      "en": "Hypertension stage 1 (>= 140/90)",
      "hi": "उच्च रक्तचाप - पहला चरण"
    },
    "applies_to": {
      "isPregnant": false
    },
    "trigger": {
      "any_of": [
        {
          "vitals.systolicBP_gte": 140
        },
        {
          "vitals.diastolicBP_gte": 90
        }
      ]
    },
    "escalates_to": "MODERATE",
    "ttt_minutes": 1440,
    "first_response_actions": [
      {
        "id": "RECHECK_2_VISITS",
        "text": {
          "en": "Recheck BP at two further visits 1 week apart before labelling hypertension."
        }
      },
      {
        "id": "PEN_PACKAGE_LINKAGE",
        "text": {
          "en": "Link with PEN package at HWC; record on NCD card."
        }
      }
    ],
    "rationale": "PEN definition of hypertension; ASHA-led screening with two-week confirmation prevents over-diagnosis.",
    "source": {
      "doc": "MoHFW-PEN-2017"
    }
  },
  {
    "id": "NCD.DIABETES.HYPER",
    "vertical": "NCD",
    "label": {
      "en": "Hyperglycaemia symptoms (?DM)",
      "hi": "मधुमेह के लक्षण"
    },
    "trigger": {
      "any_symptom_in": [
        "frequent urination",
        "polyuria",
        "polydipsia",
        "increased thirst",
        "unexplained weight loss",
        "barbar peshab",
        "bahut pyaas"
      ]
    },
    "escalates_to": "MODERATE",
    "ttt_minutes": 1440,
    "first_response_actions": [
      {
        "id": "RBS_AT_HWC",
        "text": {
          "en": "Refer to HWC for random blood-glucose check today."
        }
      }
    ],
    "rationale": "Classic osmotic symptoms warrant same-day RBS per PEN diabetes algorithm.",
    "source": {
      "doc": "MoHFW-PEN-2017",
      "section": "Diabetes"
    }
  },
  {
    "id": "HBNC.NEONATE.DANGER_SIGN",
    "vertical": "HBNC",
    "label": {
      "en": "Newborn (< 2 mo) danger sign",
      "hi": "नवजात का खतरनाक संकेत"
    },
    "applies_to": {
      "ageMonthsMin": 0,
      "ageMonthsMax": 1
    },
    "trigger": {
      "any_symptom_in": [
        "not feeding well",
        "stops feeding",
        "convulsion",
        "fast breathing",
        "severe chest indrawing",
        "fever 37.5",
        "low body temperature",
        "movement only when stimulated",
        "no movement",
        "yellow palms",
        "yellow soles",
        "dudh nahi pee raha",
        "shareer thanda",
        "shareer garam"
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 30,
    "first_response_actions": [
      {
        "id": "KMC",
        "text": {
          "en": "Initiate kangaroo mother care; keep skin-to-skin under mother's clothing with cap and socks."
        }
      },
      {
        "id": "CONTINUE_BREASTFEED_IF_ABLE",
        "text": {
          "en": "Encourage exclusive breastfeeding; if newborn cannot suckle, give expressed breast milk by spoon."
        }
      },
      {
        "id": "REFER_SNCU_NBSU",
        "text": {
          "en": "Refer to nearest SNCU / NBSU urgently; communicate findings on the HBNC card."
        }
      }
    ],
    "rationale": "MoHFW HBNC operational guidelines list seven neonatal danger signs; presence of any one mandates urgent referral with KMC en route.",
    "source": {
      "doc": "MoHFW-HBNC-2014",
      "section": "Module 5 Neonatal Danger Signs"
    }
  },
  {
    "id": "HBNC.NEONATE.HYPOTHERMIA",
    "vertical": "HBNC",
    "label": {
      "en": "Neonatal hypothermia (< 36.5 °C)",
      "hi": "नवजात का शरीर ठंडा"
    },
    "applies_to": {
      "ageMonthsMin": 0,
      "ageMonthsMax": 1
    },
    "trigger": {
      "vitals.temperature_lt": 36.5
    },
    "escalates_to": "HIGH",
    "ttt_minutes": 60,
    "first_response_actions": [
      {
        "id": "KMC_NOW",
        "text": {
          "en": "Begin kangaroo mother care immediately; cover mother and baby together."
        }
      },
      {
        "id": "WARM_ROOM",
        "text": {
          "en": "Move to a warm room; close windows; remove wet clothes."
        }
      },
      {
        "id": "RECHECK_TEMP_30MIN",
        "text": {
          "en": "Recheck axillary temperature in 30 minutes; refer if not improving or below 35 °C."
        }
      }
    ],
    "rationale": "Axillary temperature < 36.5 °C is hypothermia per HBNC; KMC restores warmth and reduces neonatal mortality.",
    "source": {
      "doc": "MoHFW-HBNC-2014",
      "section": "Module 4 Thermal Care"
    }
  },
  {
    "id": "HBNC.LBW",
    "vertical": "HBNC",
    "label": {
      "en": "Low-birth-weight newborn (< 2.5 kg)",
      "hi": "कम वज़न का नवजात"
    },
    "applies_to": {
      "ageMonthsMin": 0,
      "ageMonthsMax": 1
    },
    "trigger": {
      "vitals.weight_lt": 2.5
    },
    "escalates_to": "HIGH",
    "ttt_minutes": 1440,
    "first_response_actions": [
      {
        "id": "KMC_DAILY",
        "text": {
          "en": "Counsel and supervise daily KMC; weigh weekly."
        }
      },
      {
        "id": "EBM_IF_NOT_SUCKLING",
        "text": {
          "en": "Expressed breast milk by spoon if unable to suckle; do not bottle-feed."
        }
      },
      {
        "id": "FOLLOW_UP_HBNC_VISITS",
        "text": {
          "en": "Conduct all HBNC visits on schedule (Days 1, 3, 7, 14, 21, 28, 42); refer if any danger sign emerges."
        }
      }
    ],
    "rationale": "Weight < 2.5 kg is LBW per HBNC and requires intensified home-based care, frequent monitoring, and KMC.",
    "source": {
      "doc": "MoHFW-HBNC-2014",
      "section": "Module 7 LBW Care"
    }
  },
  {
    "id": "PPH.PRIMARY",
    "vertical": "PPH",
    "label": {
      "en": "Primary postpartum haemorrhage",
      "hi": "प्रसवोपरांत रक्तस्राव"
    },
    "applies_to": {
      "isPostpartum": true,
      "daysPostpartumMax": 1
    },
    "trigger": {
      "any_of": [
        {
          "vitals.bloodLossMl_gte": 500
        },
        {
          "any_symptom_in": [
            "heavy bleeding",
            "soaking pad",
            "khoon bahut",
            "haemorrhage",
            "rakta srava"
          ]
        }
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 0,
    "first_response_actions": [
      {
        "id": "UTERINE_MASSAGE",
        "text": {
          "en": "Perform firm bimanual fundal massage; help uterus contract."
        }
      },
      {
        "id": "EMPTY_BLADDER",
        "text": {
          "en": "Encourage the woman to empty bladder; catheterise if trained."
        }
      },
      {
        "id": "CALL_108_OBSTETRIC",
        "text": {
          "en": "Call 108 — request obstetric ambulance with blood-bank linked facility."
        }
      },
      {
        "id": "PREPARE_OXYTOCIN_AT_PHC",
        "text": {
          "en": "Communicate to PHC/CHC: prepare oxytocin / methergine / TXA per Dakshata PPH protocol."
        }
      },
      {
        "id": "KEEP_WARM_RAISE_LEGS",
        "text": {
          "en": "Keep the mother warm; raise her legs; record pad count and BP every 5 minutes."
        }
      }
    ],
    "rationale": "Estimated blood loss >= 500 mL after vaginal delivery (or saturated pads / clinical signs of shock) defines primary PPH per Dakshata; bimanual massage + uterotonics + transfer save lives.",
    "source": {
      "doc": "MoHFW-DAKSHATA-2017",
      "section": "PPH Active Management"
    }
  },
  {
    "id": "PPH.SECONDARY",
    "vertical": "PPH",
    "label": {
      "en": "Secondary PPH (24 h – 6 weeks postpartum)",
      "hi": "देर से प्रसवोपरांत रक्तस्राव"
    },
    "applies_to": {
      "isPostpartum": true,
      "daysPostpartumMin": 1,
      "daysPostpartumMax": 42
    },
    "trigger": {
      "any_symptom_in": [
        "heavy bleeding",
        "foul discharge",
        "khoon bahut",
        "vomiting",
        "fever postpartum"
      ]
    },
    "escalates_to": "HIGH",
    "ttt_minutes": 240,
    "first_response_actions": [
      {
        "id": "REFER_PHC_TODAY",
        "text": {
          "en": "Refer to PHC/CHC today for uterine assessment and possible retained products of conception."
        }
      },
      {
        "id": "MONITOR_VITALS",
        "text": {
          "en": "Record BP, pulse, temperature; watch for signs of sepsis."
        }
      }
    ],
    "rationale": "Secondary PPH commonly indicates retained products or endometritis and requires same-day facility-based assessment.",
    "source": {
      "doc": "MoHFW-DAKSHATA-2017",
      "section": "Secondary PPH"
    }
  },
  {
    "id": "PNC.SEPSIS",
    "vertical": "PNC",
    "label": {
      "en": "Postpartum sepsis",
      "hi": "प्रसवोपरांत संक्रमण"
    },
    "applies_to": {
      "isPostpartum": true,
      "daysPostpartumMax": 42
    },
    "trigger": {
      "any_of": [
        {
          "all_of": [
            {
              "vitals.temperature_gte": 38.5
            },
            {
              "any_symptom_in": [
                "foul discharge",
                "lower abdominal pain",
                "uterine tenderness"
              ]
            }
          ]
        },
        {
          "any_symptom_in": [
            "foul lochia",
            "rigors postpartum"
          ]
        }
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 60,
    "first_response_actions": [
      {
        "id": "REFER_FRU",
        "text": {
          "en": "Refer to FRU/CHC for IV antibiotics and obstetric review."
        }
      },
      {
        "id": "MONITOR_VITALS",
        "text": {
          "en": "Monitor temperature, pulse, BP every 15 minutes en route."
        }
      }
    ],
    "rationale": "Maternal temperature >= 38.5 °C plus uterine tenderness or foul discharge in the first 42 postpartum days is presumed puerperal sepsis and needs IV antibiotics within an hour.",
    "source": {
      "doc": "MoHFW-DAKSHATA-2017",
      "section": "Puerperal sepsis"
    }
  },
  {
    "id": "RBSK.DEFECT.BIRTH",
    "vertical": "RBSK",
    "label": {
      "en": "Defect at birth observed",
      "hi": "जन्मजात विकार"
    },
    "applies_to": {
      "ageMonthsMax": 1
    },
    "trigger": {
      "any_symptom_in": [
        "cleft lip",
        "cleft palate",
        "club foot",
        "talipes",
        "myelomeningocele",
        "spina bifida",
        "anorectal malformation",
        "imperforate anus",
        "down syndrome features",
        "hole in heart",
        "neural tube defect"
      ]
    },
    "escalates_to": "HIGH",
    "ttt_minutes": 1440,
    "first_response_actions": [
      {
        "id": "REFER_DEIC",
        "text": {
          "en": "Refer to nearest District Early Intervention Centre (DEIC) for definitive evaluation under RBSK."
        }
      },
      {
        "id": "RECORD_RBSK_FORM",
        "text": {
          "en": "Fill RBSK 4D form; counsel parents on free management package."
        }
      }
    ],
    "rationale": "RBSK ensures free surgical / specialist care for selected birth defects; early referral is the difference between repair and disability.",
    "source": {
      "doc": "MoHFW-RBSK-2013"
    }
  },
  {
    "id": "RBSK.DEVELOPMENTAL.DELAY",
    "vertical": "RBSK",
    "label": {
      "en": "Developmental delay screen",
      "hi": "विकास में देरी"
    },
    "applies_to": {
      "ageMonthsMin": 6,
      "ageMonthsMax": 71
    },
    "trigger": {
      "any_symptom_in": [
        "not sitting at 9 months",
        "not walking at 18 months",
        "no speech at 2 years",
        "no eye contact",
        "not responding to sounds",
        "milestone delay"
      ]
    },
    "escalates_to": "MODERATE",
    "ttt_minutes": 1440,
    "first_response_actions": [
      {
        "id": "DEIC_REFERRAL",
        "text": {
          "en": "Refer to DEIC for developmental assessment."
        }
      }
    ],
    "rationale": "RBSK uses age-appropriate milestone red flags; DEIC offers physiotherapy, speech and audiology services free of cost.",
    "source": {
      "doc": "MoHFW-RBSK-2013"
    }
  },
  {
    "id": "BITE.SNAKE",
    "vertical": "BITE",
    "label": {
      "en": "Snake bite",
      "hi": "साँप का काटना"
    },
    "trigger": {
      "any_of": [
        {
          "mechanism_in": [
            "snake bite",
            "snake",
            "saap kaata",
            "naag",
            "cobra",
            "viper"
          ]
        },
        {
          "any_symptom_in": [
            "snake bite",
            "fang marks",
            "saap ne kaata",
            "puncture wound leg"
          ]
        }
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 30,
    "first_response_actions": [
      {
        "id": "REASSURE_IMMOBILISE",
        "text": {
          "en": "Reassure the patient; immobilise the bitten limb at heart level; remove rings/bangles."
        }
      },
      {
        "id": "PRESSURE_IMMOBILISATION_NOT_TOURNIQUET",
        "text": {
          "en": "Apply pressure-immobilisation bandage; do NOT apply a tourniquet, do NOT cut, suck, or wash the wound."
        }
      },
      {
        "id": "TRANSPORT_FAST_QUIET",
        "text": {
          "en": "Transport quickly and quietly; minimise muscular movement."
        }
      },
      {
        "id": "ASV_AT_PHC",
        "text": {
          "en": "Communicate to PHC/CHC: prepare polyvalent ASV per National Snakebite Protocol."
        }
      }
    ],
    "rationale": "ASV must be given as early as possible; pressure-immobilisation slows venom spread, traditional remedies (cutting, sucking, plant pastes) are contraindicated.",
    "source": {
      "doc": "MoHFW-SNAKEBITE-2017"
    }
  },
  {
    "id": "BITE.DOG.RABIES",
    "vertical": "BITE",
    "label": {
      "en": "Dog / animal bite (rabies risk)",
      "hi": "कुत्ते / जानवर का काटना"
    },
    "trigger": {
      "any_of": [
        {
          "mechanism_in": [
            "dog bite",
            "monkey bite",
            "cat bite",
            "kutta kaata",
            "bandar kaata"
          ]
        },
        {
          "any_symptom_in": [
            "dog bite",
            "animal bite",
            "kutta ne kaata",
            "scratch by dog"
          ]
        }
      ]
    },
    "escalates_to": "HIGH",
    "ttt_minutes": 240,
    "first_response_actions": [
      {
        "id": "WASH_WOUND_15MIN",
        "text": {
          "en": "Wash the wound thoroughly with soap and running water for at least 15 minutes."
        }
      },
      {
        "id": "ANTISEPTIC",
        "text": {
          "en": "Apply povidone-iodine or 70 % alcohol after washing."
        }
      },
      {
        "id": "REFER_ARV_CATEGORY",
        "text": {
          "en": "Refer to ARV centre today; categorise per WHO/MoHFW (I/II/III) for ARV ± RIG."
        }
      },
      {
        "id": "TETANUS_PROPHYLAXIS",
        "text": {
          "en": "Update tetanus immunisation if last dose > 5 years."
        }
      }
    ],
    "rationale": "Category II/III animal bites require post-exposure prophylaxis with anti-rabies vaccine; rabies is invariably fatal once symptomatic.",
    "source": {
      "doc": "MoHFW-IDSP-2018",
      "section": "National Rabies Control Programme"
    }
  },
  {
    "id": "BITE.SCORPION",
    "vertical": "BITE",
    "label": {
      "en": "Scorpion sting",
      "hi": "बिच्छू का डंक"
    },
    "trigger": {
      "any_of": [
        {
          "mechanism_in": [
            "scorpion",
            "bichu kaata"
          ]
        },
        {
          "any_symptom_in": [
            "scorpion sting",
            "bichu ne kaata"
          ]
        }
      ]
    },
    "escalates_to": "HIGH",
    "ttt_minutes": 240,
    "first_response_actions": [
      {
        "id": "REASSURE_IMMOBILISE",
        "text": {
          "en": "Reassure; immobilise the limb; apply cold compress."
        }
      },
      {
        "id": "REFER_PHC_PRAZOSIN",
        "text": {
          "en": "Refer to PHC/CHC for prazosin and observation."
        }
      }
    ],
    "rationale": "Indian red scorpion stings can cause severe autonomic storms; oral prazosin under observation reduces mortality.",
    "source": {
      "doc": "MoHFW-IDSP-2018"
    }
  },
  {
    "id": "TB.PRESUMPTIVE",
    "vertical": "TB",
    "label": {
      "en": "Presumptive TB - cough >= 2 weeks",
      "hi": "टीबी की संभावना"
    },
    "trigger": {
      "any_of": [
        {
          "any_symptom_in": [
            "cough for 2 weeks",
            "cough for two weeks",
            "cough for 3 weeks",
            "cough for one month",
            "do haftay se khansi",
            "haftay bhar se khansi",
            "haemoptysis",
            "blood in sputum",
            "khansi mein khoon",
            "weight loss",
            "evening fever",
            "night sweats"
          ]
        }
      ]
    },
    "escalates_to": "HIGH",
    "ttt_minutes": 1440,
    "first_response_actions": [
      {
        "id": "REFER_DMC_NAAT",
        "text": {
          "en": "Refer to nearest Designated Microscopy Centre / NAAT (CB-NAAT) facility for two sputum samples (spot + early morning)."
        }
      },
      {
        "id": "INFECTION_CONTROL_HOME",
        "text": {
          "en": "Counsel cough hygiene; ventilate room; mask while coughing."
        }
      },
      {
        "id": "CONTACT_SCREENING",
        "text": {
          "en": "List household contacts < 6 yr for IPT/TPT screening per RNTCP."
        }
      }
    ],
    "rationale": "RNTCP defines presumptive TB as cough >= 2 weeks (or any duration with haemoptysis/loss of weight/night sweats); two sputum samples + NAAT is the diagnostic standard.",
    "source": {
      "doc": "MoHFW-RNTCP-2019",
      "section": "Presumptive TB Identification"
    }
  },
  {
    "id": "TB.DOTS.MISSED_DOSE",
    "vertical": "TB",
    "label": {
      "en": "DOTS dose missed",
      "hi": "डॉट्स की खुराक छूट गई"
    },
    "trigger": {
      "any_symptom_in": [
        "missed tb dose",
        "skipped dots",
        "no medicine today",
        "tb dawai chod di",
        "dots miss"
      ]
    },
    "escalates_to": "MODERATE",
    "ttt_minutes": 1440,
    "first_response_actions": [
      {
        "id": "RESTART_DOSE_SAME_DAY",
        "text": {
          "en": "Give the missed dose the same day if not yet bedtime; otherwise resume next scheduled dose."
        }
      },
      {
        "id": "NOTIFY_TBHV",
        "text": {
          "en": "Inform TB Health Visitor / Senior Treatment Supervisor; record in Nikshay."
        }
      }
    ],
    "rationale": "Adherence is essential to prevent MDR-TB; RNTCP mandates same-day dose recovery and Nikshay tracking.",
    "source": {
      "doc": "MoHFW-RNTCP-2019",
      "section": "DOTS Adherence"
    }
  },
  {
    "id": "TRAUMA.PENETRATING.GUNSHOT",
    "vertical": "TRAUMA",
    "label": {
      "en": "Penetrating injury / gunshot wound",
      "hi": "गोली लगने / पैनेट्रेटिंग चोट"
    },
    "trigger": {
      "any_of": [
        {
          "mechanism_in": [
            "gunshot",
            "bullet",
            "stab",
            "penetrating",
            "knife",
            "goli",
            "chura"
          ]
        },
        {
          "any_symptom_in": [
            "gunshot wound",
            "stab wound",
            "penetrating injury",
            "goli lagi",
            "chura lagi"
          ]
        }
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 0,
    "first_response_actions": [
      {
        "id": "CALL_108",
        "text": {
          "en": "Call 108 immediately and request a trauma-equipped ambulance.",
          "hi": "108 पर तुरंत कॉल करें और ट्रॉमा एम्बुलेंस मांगें।"
        }
      },
      {
        "id": "DIRECT_PRESSURE",
        "text": {
          "en": "Apply firm direct pressure to any bleeding wound with a clean cloth.",
          "hi": "खून बहने वाले घाव पर साफ कपड़े से सीधा दबाव डालें।"
        }
      },
      {
        "id": "DO_NOT_REMOVE_OBJECT",
        "text": {
          "en": "Do NOT remove embedded objects; stabilise them in place.",
          "hi": "घाव में फँसी वस्तु को न निकालें; उसे यथास्थान रखें।"
        }
      },
      {
        "id": "KEEP_WARM",
        "text": {
          "en": "Keep the patient lying flat and warm.",
          "hi": "मरीज को सीधा लिटाएं और गर्म रखें।"
        }
      },
      {
        "id": "NPO",
        "text": {
          "en": "Nothing by mouth — no food or water.",
          "hi": "कुछ भी खाने-पीने को न दें।"
        }
      },
      {
        "id": "MONITOR_VITALS",
        "text": {
          "en": "Monitor breathing and pulse every 2 minutes until handoff.",
          "hi": "हर 2 मिनट में साँस और नाड़ी जाँचते रहें।"
        }
      }
    ],
    "referral_text_templates": {
      "asha_to_phc": {
        "en": "TRAUMA ALERT — penetrating injury. Mechanism: {{mechanisms}}. Vitals: BP {{sbp}}/{{dbp}}, HR {{hr}}, SpO2 {{spo2}}. Direct pressure applied. 108 dispatched. Request blood and surgical readiness."
      },
      "patient_instruction": {
        "hi": "अभी अस्पताल जाना ज़रूरी है। 108 बुला ली है। शांत रहिए, हम साथ हैं।",
        "en": "We need to go to the hospital right now. 108 has been called. Stay calm — I'm with you."
      }
    },
    "rationale": "Penetrating injuries — gunshot or stab wounds — carry an immediate risk of haemorrhagic shock and require trauma-centre care within the golden hour, well before any vital sign derangement is observed.",
    "source": {
      "doc": "MoHFW-MH-OG-2017",
      "section": "Annex - Pre-hospital Trauma Care"
    }
  },
  {
    "id": "TRAUMA.MAJOR.BLEEDING",
    "vertical": "TRAUMA",
    "label": {
      "en": "Uncontrolled major external bleeding",
      "hi": "अनियंत्रित अधिक रक्तस्राव"
    },
    "trigger": {
      "any_of": [
        {
          "any_symptom_in": [
            "heavy bleeding",
            "haemorrhage",
            "uncontrolled bleeding",
            "bahut khoon",
            "khoon nikal raha",
            "blood spurting",
            "soaking",
            "rakta srava"
          ]
        },
        {
          "vitals.bloodLossMl_gte": 500
        }
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 0,
    "first_response_actions": [
      {
        "id": "DIRECT_PRESSURE_FIRM",
        "text": {
          "en": "Apply firm direct pressure with a clean cloth for at least 10 minutes without lifting."
        }
      },
      {
        "id": "ELEVATE_LIMB",
        "text": {
          "en": "If a limb is bleeding, elevate it above the level of the heart while maintaining pressure."
        }
      },
      {
        "id": "TOURNIQUET_LAST_RESORT",
        "text": {
          "en": "Apply a tourniquet 5 cm above the wound only if bleeding cannot be controlled with pressure; note the exact time."
        }
      },
      {
        "id": "CALL_108",
        "text": {
          "en": "Call 108 immediately."
        }
      },
      {
        "id": "PREVENT_SHOCK",
        "text": {
          "en": "Lay patient flat, keep warm with a blanket, do not give food or water."
        }
      }
    ],
    "rationale": "Class III/IV haemorrhage (>=750–1500 mL) reliably produces shock; ASHA-level intervention is direct pressure and rapid transport. NHM Pre-hospital trauma module mandates 108 dispatch for any uncontrolled external bleeding.",
    "source": {
      "doc": "MoHFW-MH-OG-2017",
      "section": "Annex - Pre-hospital Trauma Care"
    }
  },
  {
    "id": "TRAUMA.HEAD.GCS_LOW",
    "vertical": "TRAUMA",
    "label": {
      "en": "Severe head injury (GCS <= 12 or unresponsive)",
      "hi": "गंभीर सिर की चोट"
    },
    "trigger": {
      "any_of": [
        {
          "vitals.gcs_lte": 12
        },
        {
          "any_symptom_in": [
            "unconscious",
            "unresponsive",
            "not waking",
            "fitting",
            "convulsion after head injury",
            "head injury",
            "scalp bleeding",
            "sir mein chot"
          ]
        }
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 0,
    "first_response_actions": [
      {
        "id": "AIRWAY_SIDE",
        "text": {
          "en": "Place patient in the recovery (lateral) position to protect airway; maintain manual jaw-thrust if breathing is noisy."
        }
      },
      {
        "id": "IMMOBILISE_NECK",
        "text": {
          "en": "Keep neck immobilised; do not flex or rotate."
        }
      },
      {
        "id": "CALL_108",
        "text": {
          "en": "Call 108 — request neurology-capable facility."
        }
      },
      {
        "id": "MONITOR_BREATHING",
        "text": {
          "en": "Watch for vomiting; keep airway clear; recheck consciousness every 2 minutes."
        }
      }
    ],
    "rationale": "GCS <= 12 or any altered consciousness after head trauma indicates moderate-to-severe TBI and requires immediate neuroimaging-capable transfer.",
    "source": {
      "doc": "MoHFW-MH-OG-2017",
      "section": "Annex - Head Injury First Aid"
    }
  },
  {
    "id": "TRAUMA.AIRWAY.COMPROMISE",
    "vertical": "TRAUMA",
    "label": {
      "en": "Airway compromise / not breathing normally",
      "hi": "साँस लेने में गंभीर रुकावट"
    },
    "trigger": {
      "any_of": [
        {
          "vitals.airwayClear": false
        },
        {
          "any_symptom_in": [
            "choking",
            "stridor",
            "gurgling",
            "agonal",
            "not breathing",
            "saans nahi le raha",
            "gasping"
          ]
        },
        {
          "vitals.spO2_lt": 90
        }
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 0,
    "first_response_actions": [
      {
        "id": "OPEN_AIRWAY",
        "text": {
          "en": "Open airway: head-tilt, chin-lift (jaw-thrust if neck injury suspected)."
        }
      },
      {
        "id": "CLEAR_SECRETIONS",
        "text": {
          "en": "Clear visible secretions/foreign body if reachable; do NOT do blind sweeps."
        }
      },
      {
        "id": "RECOVERY_POSITION",
        "text": {
          "en": "Place in recovery position once airway is open."
        }
      },
      {
        "id": "CALL_108",
        "text": {
          "en": "Call 108 immediately."
        }
      }
    ],
    "rationale": "Compromised airway and SpO2 < 90% are pre-arrest signs; any other priority (history, paperwork) must wait.",
    "source": {
      "doc": "MoHFW-MH-OG-2017",
      "section": "Annex - ABC Resuscitation"
    }
  },
  {
    "id": "TRAUMA.BURN.MAJOR",
    "vertical": "TRAUMA",
    "label": {
      "en": "Major burn (>=15% body surface, face/airway, deep)",
      "hi": "गंभीर जलना"
    },
    "trigger": {
      "any_of": [
        {
          "mechanism_in": [
            "burn",
            "scald",
            "fire",
            "jal gaya",
            "agni",
            "boiling water"
          ]
        },
        {
          "any_symptom_in": [
            "burn",
            "scald",
            "burnt skin",
            "facial burn",
            "airway burn",
            "jal gaya hai"
          ]
        }
      ]
    },
    "escalates_to": "HIGH",
    "ttt_minutes": 60,
    "first_response_actions": [
      {
        "id": "COOL_WATER_20MIN",
        "text": {
          "en": "Cool the burn with running cool (not cold) water for at least 20 minutes."
        }
      },
      {
        "id": "REMOVE_JEWELLERY",
        "text": {
          "en": "Remove rings, bangles, watches before swelling; do NOT peel stuck cloth."
        }
      },
      {
        "id": "COVER_CLEAN",
        "text": {
          "en": "Cover the burn loosely with a clean dry cloth; do NOT apply oil/toothpaste/ash."
        }
      },
      {
        "id": "FLUIDS_SIPS",
        "text": {
          "en": "Encourage small sips of ORS if conscious and not vomiting."
        }
      },
      {
        "id": "CALL_108_IF_FACE_OR_LARGE",
        "text": {
          "en": "Call 108 for any burn involving face, hands, genitals, or larger than the patient's palm."
        }
      }
    ],
    "rationale": "Domestic kitchen and stove burns are common in rural India; first 20 minutes of cool-water irrigation drastically reduces depth. NHM HBNC module Section 7.4 mandates non-occlusive clean dressing and prohibits traditional remedies.",
    "source": {
      "doc": "MoHFW-HBNC-2014",
      "section": "7.4 First aid for burns"
    }
  },
  {
    "id": "TRAUMA.FRACTURE.SUSPECTED",
    "vertical": "TRAUMA",
    "label": {
      "en": "Suspected fracture or limb deformity",
      "hi": "हड्डी टूटने का संदेह"
    },
    "trigger": {
      "any_of": [
        {
          "mechanism_in": [
            "fracture",
            "fall",
            "rta",
            "road accident",
            "haddi tooti",
            "gir gaya"
          ]
        },
        {
          "any_symptom_in": [
            "deformity",
            "fracture",
            "broken bone",
            "haddi tooti",
            "limb swelling after injury",
            "cannot move limb"
          ]
        }
      ]
    },
    "escalates_to": "HIGH",
    "ttt_minutes": 120,
    "first_response_actions": [
      {
        "id": "IMMOBILISE",
        "text": {
          "en": "Immobilise the limb in the position found using a splint, cardboard, or rolled cloth."
        }
      },
      {
        "id": "ELEVATE_AND_ICE",
        "text": {
          "en": "Elevate the limb if possible; apply a cool compress (no direct ice on skin)."
        }
      },
      {
        "id": "CHECK_DISTAL_PULSE",
        "text": {
          "en": "Check pulse and sensation distal to the injury; if absent, escalate immediately."
        }
      },
      {
        "id": "ARRANGE_TRANSPORT",
        "text": {
          "en": "Arrange transport to PHC/CHC for X-ray and orthopaedic review."
        }
      }
    ],
    "rationale": "Closed fractures rarely cause immediate mortality but require X-ray, reduction, and immobilisation; open fractures or absent distal pulses must be escalated to CRITICAL via airway/bleeding rules.",
    "source": {
      "doc": "MoHFW-MH-OG-2017",
      "section": "Annex - Limb Injury First Aid"
    }
  },
  {
    "id": "TRAUMA.SHOCK.HEMODYNAMIC",
    "vertical": "TRAUMA",
    "label": {
      "en": "Shock (hypotension or tachycardia after trauma)",
      "hi": "ट्रॉमा के बाद शॉक"
    },
    "trigger": {
      "all_of": [
        {
          "any_of": [
            {
              "mechanism_in": [
                "fall",
                "rta",
                "road accident",
                "fracture",
                "burn",
                "gunshot",
                "stab"
              ]
            },
            {
              "any_symptom_in": [
                "accident",
                "fall",
                "trauma",
                "injury"
              ]
            }
          ]
        },
        {
          "any_of": [
            {
              "vitals.systolicBP_lt": 90
            },
            {
              "vitals.heartRate_gte": 120
            }
          ]
        }
      ]
    },
    "escalates_to": "CRITICAL",
    "ttt_minutes": 30,
    "first_response_actions": [
      {
        "id": "LAY_FLAT_LEGS_UP",
        "text": {
          "en": "Lay the patient flat and elevate the legs 30 cm if no spinal/leg injury."
        }
      },
      {
        "id": "KEEP_WARM",
        "text": {
          "en": "Cover with a blanket; do not let the patient become cold."
        }
      },
      {
        "id": "CALL_108",
        "text": {
          "en": "Call 108 immediately."
        }
      },
      {
        "id": "NPO",
        "text": {
          "en": "Nothing by mouth."
        }
      }
    ],
    "rationale": "Shock-index (HR/SBP) > 1 or SBP < 90 mmHg after trauma indicates compensated/early-decompensated shock; immediate transfer is mandatory regardless of mechanism.",
    "source": {
      "doc": "MoHFW-MH-OG-2017",
      "section": "Annex - Trauma Triage"
    }
  }
] as unknown as ProtocolRule[];

export type Severity = "LOW" | "MODERATE" | "HIGH" | "CRITICAL";

export interface ProtocolRule {
  id: string;
  vertical: string;
  label: { en: string; [k: string]: string | undefined };
  applies_to?: Record<string, number | boolean | undefined>;
  trigger: TriggerExpr;
  escalates_to: Severity;
  ttt_minutes?: number;
  first_response_actions?: Array<{
    id: string;
    text: { en: string; [k: string]: string | undefined };
  }>;
  referral_text_templates?: {
    asha_to_phc?: { en: string; [k: string]: string | undefined };
    patient_instruction?: { en: string; [k: string]: string | undefined };
  };
  rationale: string;
  source: { doc: string; section?: string; url?: string };
  version?: string;
}

export type TriggerExpr =
  | { all_of: TriggerExpr[] }
  | { any_of: TriggerExpr[] }
  | { not: TriggerExpr }
  | { [key: string]: unknown };
